In [4]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv("online_retail_II.csv")

Saving online_retail_II.csv to online_retail_II (2).csv

In [5]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

# Display Settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [6]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df = pd.read_csv("online_retail_II.csv")

In [9]:
df.shape

(1067371, 8)

Check Missing Values

In [11]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

Check Duplicate Rows

In [12]:
df.duplicated().sum()

np.int64(34335)

Check Dataset Size

In [13]:
df.shape

(1067371, 8)

Remove Missing Customer IDs

In [14]:
df = df.dropna(subset=['Customer ID'])

Convert Customer ID to Integer

In [15]:
df['Customer ID'] = df['Customer ID'].astype(int)

Check for Cancelled Orders

In [16]:
df[df['Invoice'].astype(str).str.startswith('C')].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321,Australia

Count Cancelled Orders

In [17]:
df['Invoice'].astype(str).str.startswith('C').sum()

np.int64(18744)

Remove Cancelled Orders

In [19]:
df = df[~df['Invoice'].astype(str).str.startswith('C')]

Remove Negative Quantities

In [20]:
df = df[df['Quantity'] > 0]

Remove Zero or Negative Prices

In [21]:
df = df[df['Price'] > 0]

Check the Final Shape

In [22]:
df.shape

(805549, 8)

Verify Data Types

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 805549 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      805549 non-null  object
 1   StockCode    805549 non-null  object
 2   Description  805549 non-null  object
 3   Quantity     805549 non-null  int64
 4   InvoiceDate  805549 non-null  object
 5   Price        805549 non-null  float64
 6   Customer ID  805549 non-null  int64
 7   Country      805549 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 55.3+ MB